-- Generated by generate_data.py. Do not edit by hand.
CREATE DATABASE IF NOT EXISTS card_analytics;
USE card_analytics;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `card_txns`;
DROP TABLE IF EXISTS `customer_master`;
DROP TABLE IF EXISTS `merchant_master`;
DROP TABLE IF EXISTS `response_master`;
DROP TABLE IF EXISTS `BIN_master`;
DROP TABLE IF EXISTS `acquirer_master`;
DROP TABLE IF EXISTS `issuer_master`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `issuer_master` (
  `id` VARCHAR(10) NOT NULL,
  `iss_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `acquirer_master` (
  `id` VARCHAR(10) NOT NULL,
  `acq_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `BIN_master` (
  `BIN` VARCHAR(6) NOT NULL,
  `card_type` VARCHAR(20) NOT NULL,
  `issuer_id` VARCHAR(10) NOT NULL,
  `card_variant` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`BIN`),
  CONSTRAINT `fk_BIN_master_issuer_id` FOREIGN KEY (`issuer_id`) REFERENCES `issuer_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `response_master` (
  `response_code` VARCHAR(2) NOT NULL,
  `response_description` VARCHAR(100) NOT NULL,
  `TD_BD` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`response_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `merchant_master` (
  `merchant_id` VARCHAR(10) NOT NULL,
  `acquirer_id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `mcc_code` VARCHAR(4) NOT NULL,
  `mcc_description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`merchant_id`),
  CONSTRAINT `fk_merchant_master_acquirer_id` FOREIGN KEY (`acquirer_id`) REFERENCES `acquirer_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `customer_master` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `card_txns` (
  `txn_id` VARCHAR(12) NOT NULL,
  `amt` DECIMAL(12,2) NOT NULL,
  `date` VARCHAR(10) NOT NULL,
  `issuer_id` VARCHAR(10) NOT NULL,
  `acquirer_id` VARCHAR(10) NOT NULL,
  `merchant_id` VARCHAR(10) NOT NULL,
  `customer_id` VARCHAR(10) NOT NULL,
  `BIN` VARCHAR(6) NOT NULL,
  `country` VARCHAR(2) NOT NULL,
  `location` VARCHAR(50) NOT NULL,
  `response_code` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`txn_id`),
  CONSTRAINT `fk_card_txns_issuer_id` FOREIGN KEY (`issuer_id`) REFERENCES `issuer_master` (`id`),
  CONSTRAINT `fk_card_txns_acquirer_id` FOREIGN KEY (`acquirer_id`) REFERENCES `acquirer_master` (`id`),
  CONSTRAINT `fk_card_txns_merchant_id` FOREIGN KEY (`merchant_id`) REFERENCES `merchant_master` (`merchant_id`),
  CONSTRAINT `fk_card_txns_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer_master` (`id`),
  CONSTRAINT `fk_card_txns_BIN` FOREIGN KEY (`BIN`) REFERENCES `BIN_master` (`BIN`),
  CONSTRAINT `fk_card_txns_response_code` FOREIGN KEY (`response_code`) REFERENCES `response_master` (`response_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
